### ISSUE TITLE
Làm sao để sử dụng tính năng DIAGRAM

### ISSUE THREAD

**Issue by susanop** [hudy9x/kompad-homepage#6]
tôi vẫn chưa biết cách sử dụng tính năng DIAGRAM. ai đó hãy hướng dẫn tôi với

**Comment by hudy9x** [comment]
@susanop  tính năng này đang được phát triển b nhé

để sử dụng thì bạn click vào button  bên dưới
![image](https://user-images.githubusercontent.com/95471659/188283360-ccdcf660-74a6-4346-97f7-dbfd799b8f88.png)

Sau đó nhập nội dung vào textbox theo cú pháp của trang [mermaid](https://mermaid-js.github.io/mermaid/#/flowchart) là được

Tuy nhiên, như đã nói ở trên, tính năng chưa được hoàn thiện nên chỉ phục vụ chính cho người phát triển thôi
